FROM nginxinc/nginx-unprivileged:1-alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./uwsgi_params /etc/nginx/uwsgi_params

USER root

RUN mkdir -p /vol/static_data
RUN chmod 755 /vol/static_data

USER nginx
