# Generated by Django 4.1.2 on 2022-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("rotation_period", models.CharField(max_length=40)),
                ("orbital_period", models.CharField(max_length=40)),
                ("diameter", models.CharField(max_length=40)),
                ("climate", models.CharField(max_length=40)),
                ("gravity", models.CharField(max_length=40)),
                ("terrain", models.CharField(max_length=40)),
                ("surface_water", models.CharField(max_length=40)),
                ("population", models.CharField(max_length=40)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
