# Generated by Django 4.1.2 on 2022-10-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("height", models.CharField(blank=True, max_length=10)),
                ("mass", models.CharField(blank=True, max_length=10)),
                ("hair_color", models.CharField(blank=True, max_length=20)),
                ("skin_color", models.CharField(blank=True, max_length=20)),
                ("eye_color", models.CharField(blank=True, max_length=20)),
                ("birth_year", models.CharField(blank=True, max_length=10)),
                ("gender", models.CharField(blank=True, max_length=40)),
                (
                    "homeworld",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents",
                        to="api.planet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
