# Generated by Django 4.1.2 on 2022-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="Starship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=40)),
                ("manufacturer", models.CharField(max_length=80)),
                ("cost_in_credits", models.CharField(max_length=40)),
                ("length", models.CharField(max_length=40)),
                ("max_atmosphering_speed", models.CharField(max_length=40)),
                ("crew", models.CharField(max_length=40)),
                ("passengers", models.CharField(max_length=40)),
                ("cargo_capacity", models.CharField(max_length=40)),
                ("consumables", models.CharField(max_length=40)),
                ("hyperdrive_rating", models.CharField(max_length=40)),
                ("MGLT", models.CharField(max_length=40)),
                ("starship_class", models.CharField(max_length=40)),
                (
                    "pilots",
                    models.ManyToManyField(
                        blank=True, related_name="starships", to="api.people"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
