# Generated by Django 4.1.2 on 2022-10-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                ("classification", models.CharField(max_length=40)),
                ("designation", models.CharField(max_length=40)),
                ("average_height", models.CharField(max_length=40)),
                ("skin_colors", models.CharField(max_length=200)),
                ("hair_colors", models.CharField(max_length=200)),
                ("eye_colors", models.CharField(max_length=200)),
                ("average_lifespan", models.CharField(max_length=40)),
                ("language", models.CharField(max_length=40)),
                (
                    "homeworld",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.planet",
                    ),
                ),
                (
                    "people",
                    models.ManyToManyField(related_name="species", to="api.people"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
