# Generated by Django 4.1.2 on 2022-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_species"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("episode_id", models.IntegerField()),
                ("opening_crawl", models.TextField(max_length=1000)),
                ("director", models.CharField(max_length=100)),
                ("producer", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                (
                    "characters",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="api.people"
                    ),
                ),
                (
                    "planets",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="api.planet"
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="api.species"
                    ),
                ),
                (
                    "starships",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="api.starship"
                    ),
                ),
                (
                    "vehicles",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="api.vehicle"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
