# Generated by Django 4.1.2 on 2022-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_film"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="episode_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="people",
            name="height",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="mass",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="diameter",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="planet",
            name="orbital_period",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="planet",
            name="population",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="planet",
            name="rotation_period",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="planet",
            name="surface_water",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="species",
            name="average_height",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="species",
            name="average_lifespan",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="starship",
            name="cargo_capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="starship",
            name="cost_in_credits",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="starship",
            name="length",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="starship",
            name="max_atmosphering_speed",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="starship",
            name="passengers",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="cargo_capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="cost_in_credits",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="length",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="max_atmosphering_speed",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="passengers",
            field=models.PositiveIntegerField(),
        ),
    ]
