# Generated by Django 4.1.2 on 2022-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_film_episode_id_alter_people_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="pilots",
        ),
        migrations.RemoveField(
            model_name="film",
            name="starships",
        ),
        migrations.RemoveField(
            model_name="film",
            name="vehicles",
        ),
        migrations.AlterField(
            model_name="people",
            name="birth_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="eye_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="gender",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="hair_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="mass",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="skin_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="climate",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="diameter",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="gravity",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="orbital_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="population",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="rotation_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="surface_water",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="terrain",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name="Starship",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
