# Generated by Django 4.1.2 on 2022-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_vehicle_pilots_remove_film_starships_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="average_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="average_lifespan",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="classification",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="designation",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="eye_colors",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="hair_colors",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="language",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="skin_colors",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
