# Generated by Django 4.1.2 on 2022-11-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("editedAt", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("alive", "Alive"),
                            ("dead", "Dead"),
                            ("unknown", "unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("genderless", "Genderless"),
                            ("unknown", "unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("species", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="The type or subspecies of the character",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="characters/avatar/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("editedAt", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "type",
                    models.CharField(
                        help_text="The type of the location, e.g Plant.", max_length=50
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        help_text="The dimension in which the location is located.",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("editedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("release", models.DateField()),
                ("season", models.PositiveSmallIntegerField()),
                ("episode", models.PositiveSmallIntegerField()),
                (
                    "characters",
                    models.ManyToManyField(related_name="episodes", to="api.character"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="character",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.location",
            ),
        ),
    ]
