# Generated by Django 3.2.14 on 2022-08-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20220809_2057"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
